---
title: "Viz 2"
author: "Steven Lawrence"
date: "October 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
install.packages("ggridges")
library(ggridges)
install.packages("rnoaa")
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```
making plots

```{r}
weather_df %>%
  mutate(
     name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```
## Reorder

```{r}
weather_df %>% 
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to= "temperature"
  ) %>% 
  ggplot(aes(y = temperature, x = name, fill = observation))+
  geom_boxplot()+
  theme(legend.position = "bottom")
```

